Script started on Tue Nov 15 10:06:08 2022
Restored session: Mon Nov 14 20:23:01 CST 2022
[1m[7m%[27m[1m[0m                                                                                                                         ]7;file://Tylers-MacBook-Pro-5.local/Users/tylerteufel/auburn/sophomore/fall/comp_2710/project5_Teufel_tdt0025[0m[27m[24m[Jtylerteufel@Tylers-MacBook-Pro-5 project5_Teufel_tdt0025 % [K[?2004h../project5_teufe     Teufel_tdt0035.   25[?2004l
Banner id: 904187486
producer produce item 7
consumer consume item 7
producer produce item 14
consumer consume item 14
producer produce item 21
consumer consume item 21
producer produce item 28
consumer consume item 28
producer produce item 35
consumer consume item 35
producer produce item 42
consumer consume item 42
producer produce item 49
consumer consume item 49
producer produce item 56
consumer consume item 56
producer produce item 63
consumer consume item 63
producer produce item 70
consumer consume item 70
[1m[7m%[27m[1m[0m                                                                                                                         ]7;file://Tylers-MacBook-Pro-5.local/Users/tylerteufel/auburn/sophomore/fall/comp_2710/project5_Teufel_tdt0025[0m[27m[24m[Jtylerteufel@Tylers-MacBook-Pro-5 project5_Teufel_tdt0025 % [K[?2004h